# Generated by Django 3.2.9 on 2021-11-26 17:45

import create.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(default=create.models.passwordGenerator, max_length=30),
        ),
    ]
